language: cpp

addons:
  artifacts:
    paths:
      - $(find $(dirname $(pwd))/obs-websocket/package)

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name xenial -v $(dirname $(pwd)):/root -w /root nimmis/ubuntu:16.04
        - docker exec -it xenial /root/obs-websocket/CI/install-dependencies-xenial.sh
      script:
        - docker exec -it xenial /root/obs-websocket/CI/build-xenial.sh
      after_success:
        - docker exec -it xenial /root/obs-websocket/CI/package-xenial.sh

    - os: osx
      osx_image: xcode8.3
      before_install: "./CI/install-dependencies-osx.sh"
      script: "./CI/build-osx.sh"
