language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: "./CI/install-dependencies-linux.sh"
      before_script: "./CI/before-script-linux.sh"

    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name xenial -v $(dirname $(pwd)):/root -w /root nimmis/ubuntu:16.04
        - docker exec -it xenial /root/obs-websocket/CI/install-dependencies-xenial.sh
      before_script:
        - docker exec -it xenial /root/obs-websocket/CI/before-script-xenial.sh

    - os: osx
      before_install: "./CI/install-dependencies-osx.sh"
      before_script: "./CI/before-script-osx.sh"

script: cd ./build && make -j4 && cd -
