language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: "./CI/install-dependencies-linux.sh"
      before_script: "./CI/before-script-linux.sh"

    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name xenial nimmis/ubuntu:16.04
        - docker ps -a
        - docker cp obs-websocket xenial:/root/
        - docker cp ./CI/install-dependencies-xenial.sh xenial:/root/
        - docker exec -it xenial /root/install-dependencies-xenial.sh
      before_script:
        - docker cp ./CI/before-script-xenial.sh xenial:/root/
        - docker exec -it xenial /root/before-script-xenial.sh

    - os: osx
      before_install: "./CI/install-dependencies-osx.sh"
      before_script: "./CI/before-script-osx.sh"

script: cd ./build && make -j4 && cd -
